# This file is a template, and might need editing before it works on your project.
# This is a sample GitLab CI/CD configuration file that should run without any modifications.
# It demonstrates a basic 3 stage CI/CD pipeline. Instead of real tests or scripts,
# it uses echo commands to simulate the pipeline execution.
#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages
#
# You can copy and paste this template into a new `.gitlab-ci.yml` file.
# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.
#
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml

stages:          # List of stages for jobs, and their order of execution
  - build

.ccache_Scripts: &ccache
  - export CCACHE_BASEDIR="$PWD"
  - export CCACHE_DIR="$PWD/ccache"
  - export CCACHE_COMPILERCHECK=content
  - export CCACHE_STATS=true
  - export CCACHE_STATSLOG="$PWD/ccache_statslog"

.aptcache_Scripts: &aptcache
  - export APT_CACHE_DIR=`pwd`/apt-cache
  - mkdir --parents --verbose $APT_CACHE_DIR/partial/
  - export DEBIAN_FRONTEND=noninteractive

default:
  image: debian:stable-slim

.job_template: &job_build # This job runs in the build stage, which runs first.
  stage: build
  variables:
    CCACHE_MAXSIZE: 50M
    GIT_STRATEGY: clone
    GIT_CLONE_PATH: $CI_BUILDS_DIR/$CI_CONCURRENT_ID/$CI_PROJECT_PATH
  cache:
    - key: ccache-$CI_PROJECT_PATH_SLUG-$CI_JOB_NAME_SLUG
      fallback_keys:
        - cache-$CI_PROJECT_PATH_SLUG-$CI_DEFAULT_BRANCH
        - cache-$CI_PROJECT_PATH_SLUG-default
      paths:
        - ccache
    - key: apt-$CI_JOB_IMAGE
      paths:
        - apt-cache
      unprotect: true
  before_script:
    - dpkg --add-architecture i386
    - dpkg --add-architecture amd64
    - dpkg --add-architecture arm64
    - apt-get --quiet --quiet update
    - *aptcache
    - apt-get --no-install-recommends --quiet --quiet --yes --option dir::cache::archives="$APT_CACHE_DIR" install apt-utils
    - apt-get --no-install-recommends --quiet --quiet --yes --option dir::cache::archives="$APT_CACHE_DIR" install make git ccache
    - *ccache
    - ccache --zero-stats || true
    - ccache --show-stats || true
  after_script:
    - *aptcache
    - apt-get --quiet --quiet --option dir::cache::archives="$APT_CACHE_DIR" autoclean
    - *ccache
    - ccache --show-stats
    - ccache --show-log-stats || true

build-testing:
  <<: *job_build
  image: debian:testing-slim
  allow_failure: true
  artifacts:
    paths:
      - "bin/lsdl2srb2*"
    name: "$CI_PROJECT_PATH_SLUG-$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA-testing"
  script:
    - *aptcache
    - apt-get --no-install-recommends --quiet --quiet --yes --option dir::cache::archives="$APT_CACHE_DIR" install gcc
    - apt-get --no-install-recommends --quiet --quiet --yes --option dir::cache::archives="$APT_CACHE_DIR" install libsdl2-mixer-dev libpng-dev libcurl4-openssl-dev libgme-dev libopenmpt-dev
    - *ccache
    - make --directory=src --keep-going CCACHE=1 ERRORMODE=1 NONX86=1 || make --directory=src --keep-going CCACHE=1 ERRORMODE=1 NONX86=1

build-i686-w64-mingw32:
  <<: *job_build
  artifacts:
    paths:
      - "bin/srb2win.exe*"
    name: "$CI_PROJECT_PATH_SLUG-$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA-Win32"
  script:
    - *aptcache
    - apt-get --no-install-recommends --quiet --quiet --yes --option dir::cache::archives="$APT_CACHE_DIR" install gcc-mingw-w64-i686-win32
    - *ccache
    - make --directory=src --keep-going CCACHE=1 ERRORMODE=1 MINGW=1 PREFIX=i686-w64-mingw32 || make --directory=src --keep-going CCACHE=1 ERRORMODE=1 MINGW=1 PREFIX=i686-w64-mingw32

build-x86_64-linux-gnu:
  <<: *job_build
  artifacts:
    paths:
      - "bin/lsdl2srb2*"
    name: "$CI_PROJECT_PATH_SLUG-$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA-x86-64"
  script:
    - *aptcache
    - apt-get --no-install-recommends --quiet --quiet --yes --option dir::cache::archives="$APT_CACHE_DIR" install gcc-x86-64-linux-gnu || apt-get --no-install-recommends --quiet --quiet --yes --option dir::cache::archives="$APT_CACHE_DIR" install gcc
    - apt-get --no-install-recommends --quiet --quiet --yes --option dir::cache::archives="$APT_CACHE_DIR" install libsdl2-mixer-dev:amd64 libpng-dev:amd64 libcurl4-openssl-dev:amd64 libgme-dev:amd64 libopenmpt-dev:amd64
    - export CC=x86_64-linux-gnu-gcc
    - export OBJCOPY=x86_64-linux-gnu-objcopy
    - export OBJDUMP=x86_64-linux-gnu-objdump
    - export PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig
    - *ccache
    - make --directory=src --keep-going CCACHE=1 ERRORMODE=1 LINUX64=1 || make --directory=src --keep-going CCACHE=1 ERRORMODE=1 LINUX64=1

build-i686-linux-gnu:
  <<: *job_build
  artifacts:
    paths:
      - "bin/lsdl2srb2*"
    name: "$CI_PROJECT_PATH_SLUG-$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA-i686"
  script:
    - *aptcache
    - apt-get --no-install-recommends --quiet --quiet --yes --option dir::cache::archives="$APT_CACHE_DIR" install gcc-i686-linux-gnu || apt-get --no-install-recommends --quiet --quiet --yes --option dir::cache::archives="$APT_CACHE_DIR" install gcc
    - apt-get --no-install-recommends --quiet --quiet --yes --option dir::cache::archives="$APT_CACHE_DIR" install libsdl2-mixer-dev:i386 libpng-dev:i386 libcurl4-openssl-dev:i386 libgme-dev:i386 libopenmpt-dev:i386
    - export CC=i686-linux-gnu-gcc
    - export OBJCOPY=i686-linux-gnu-objcopy
    - export OBJDUMP=i686-linux-gnu-objdump
    - export PKG_CONFIG_PATH=/usr/lib/i386-linux-gnu/pkgconfig
    - *ccache
    - make --directory=src --keep-going CCACHE=1 ERRORMODE=1 LINUX=1 || make --directory=src --keep-going CCACHE=1 ERRORMODE=1 LINUX=1

build-aarch64-linux-gnu:
  <<: *job_build
  artifacts:
    paths:
      - "bin/lsdl2srb2*"
    name: "$CI_PROJECT_PATH_SLUG-$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA-aarch64"
  script:
    - *aptcache
    - apt-get --no-install-recommends --quiet --quiet --yes --option dir::cache::archives="$APT_CACHE_DIR" install gcc-aarch64-linux-gnu || apt-get --no-install-recommend --quiet --quiet --yes --option dir::cache::archives="$APT_CACHE_DIR" install  gcc
    - apt-get --no-install-recommends --quiet --quiet --yes --option dir::cache::archives="$APT_CACHE_DIR" install libsdl2-mixer-dev:arm64 libpng-dev:arm64 libcurl4-openssl-dev:arm64 libgme-dev:arm64 libopenmpt-dev:arm64
    - export CC=aarch64-linux-gnu-gcc
    - export OBJCOPY=aarch64-linux-gnu-objcopy
    - export OBJDUMP=aarch64-linux-gnu-objdump
    - export PKG_CONFIG_PATH=/usr/lib/aarch64-linux-gnu/pkgconfig
    - *ccache
    - make --directory=src --keep-going CCACHE=1 ERRORMODE=1 LINUX64=1 NONX86=1 || make --directory=src --keep-going CCACHE=1 ERRORMODE=1 LINUX64=1 NONX86=1

build-x86_64-w64-mingw32:
  <<: *job_build
  artifacts:
    paths:
      - "bin/srb2win64.exe*"
    name: "$CI_PROJECT_PATH_SLUG-$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA-Win64"
  script:
    - *aptcache
    - apt-get --no-install-recommends --quiet --quiet --yes --option dir::cache::archives="$APT_CACHE_DIR" install gcc-mingw-w64-x86-64-win32
    - *ccache
    - make --directory=src --keep-going CCACHE=1 ERRORMODE=1 MINGW64=1 PREFIX=x86_64-w64-mingw32 || make --directory=src --keep-going CCACHE=1 ERRORMODE=1 MINGW64=1 PREFIX=x86_64-w64-mingw32
