language: c

sudo: required
dist: trusty

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
    - libsdl2-mixer-dev
    - libpng-dev
    - libgl1-mesa-dev
    - libgme-dev
    - p7zip-full

before_install:
  - cmake --version

before_script:
  - make cache
  - wget http://rosenthalcastle.org/srb2/SRB2-v2114-Installer.exe -c -O cache/SRB2-v2114-Installer.exe
  - 7z x cache/SRB2-v2114-Installer.exe -o assets
  - mkdir build
  - cd build
  - cmake ..

