sudo: required
dist: trusty

compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
    - george-edison55-precise-backports
    packages:
    - cmake
    - cmake-data
    - libsdl2-mixer-dev
    - libpng-dev
    - libgl1-mesa-dev

before_install:
  - cmake --version

before_script:
  - mkdir build
  - cd build
  - cmake ..
