language: c

sudo: required

os:
  - linux
  #- osx

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
    - libsdl2-mixer-dev
    - libpng-dev
    - ibgl1-mesa-dev

before_install:
  - cmake --version

before_script:
  - mkdir build
  - cd build
  - cmake ..
