sudo: required
dist: trusty

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
    - libsdl2-mixer-dev
    - libpng-dev
    - libgl1-mesa-dev
    - libgme-dev
    - p7zip

before_install:
  - cmake --version

before_script:
  - curl http://rosenthalcastle.org/srb2/SRB2-v2114-Installer.exe -o cache/SRB2-v2114-Installer.exe
  - 7z x cache/SRB2-v2114-Installer.exe -o assets
  - mkdir build
  - cd build
  - cmake ..

install: false

cache:
  - ccache
  directories:
    - cache
