version: 2.1.14.{branch}-{build}
os: MinGW

environment:
 CC: i686-w64-mingw32-gcc
 WINDRES: windres
 MINGW_SDK: c:\msys64\mingw32
 CFLAGS: -Wall -W -Werror

install:

before_build:
- set Path=%MINGW_SDK%\bin;%Path%
- i686-w64-mingw32-gcc --version
- mingw32-make --version
- set SRB2_MFLAGS=-C src MINGW=1 WARNINGMODE=1 NOASM=1 NOUPX=1 GCC53=1

build_script:
- cmd: mingw32-make.exe %SRB2_MFLAGS% SDL=1 clean
- cmd: mingw32-make.exe %SRB2_MFLAGS% SDL=1 ERRORMODE=1

after_build:
- cmd: git rev-parse --short %APPVEYOR_REPO_COMMIT%>%TMP%/gitshort.txt
- cmd: set /P GITSHORT=<%TMP%/gitshort.txt
- set BUILD_ARCHIVE=%APPVEYOR_REPO_BRANCH%-%GITSHORT%.7z
- cmd: 7z a %BUILD_ARCHIVE% bin\Mingw\Release -xr!.gitignore
- appveyor PushArtifact %BUILD_ARCHIVE%

test: off

deploy:
  - provider: FTP
    protocol: ftps
    host: 
      secure: NsLJEPIBvmwCOj8Tg8RoRQ==
    username:
      secure: ejxi5mvk7oLYu7QtbYojajEPigMy0mokaKhuEVuDZcA=
    password:
      secure: Hbn6Uy3lT0YZ88yFJ3aW4w==
    folder: appveyor
    application:
    active_mode: false


on_finish:
#- cmd: echo xfreerdp /u:appveyor /cert-ignore +clipboard /v:<ip>:<port>
#- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
