name: Android CI

on:
  push:
    branches: [ "androidmain" ]
  pull_request:
    branches: [ "androidmain" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Build with Gradle
      run: cd android && ./gradlew assemblegameFull
    - uses: actions/upload-artifact@v3
      with:
        name: srb2-tsourd3rd
        path: android/app/build/outputs/apk/gameFull/
